SLOP_FEATURES = [
    "An emoji and a 'it's not X, it's Y' headline",
    "An opening about what too many people do wrong",
    "A numbered list (3-5 items)",
    "Corporate buzzwords like 'synergy,' 'leverage,' 'scalable,' 'pain points'",
    "At least one mathematical formula metaphor (e.g., 'X + Y = Z')",
    "An alliterative phrase",
    "A 'Stop [X]. Start [Y].' statement",
    "End with a light bulb emoji and engagement question",
    "2-6 relevant hashtags",
]


CLEAN_UP_RULES = [
    "Remove any 'it's not X, it's Y'-style language",
    "Refrain from using emojis",
    "Remove any **bold** text, especially after a bullet point",
    "Replace buzzwords with specific, concrete language",
    "Convert vague platitudes into actual actionable advice or omit it when there's no real content",
    "Remove any false dichotomies and artificial urgency",
    "If a point is substantive, keep it but make it direct",
    "If a point is empty filler, cut it",
    "Remove the 'engagement bait' question at the end (if there is one)",
    "Remove hashtags",
    "Write like a human having a real conversation",
]


TOPICS = {
    "Professional development": [
        [
            "discussing some aspect of leadership and management",
            "on making the most of your organization's leadership and management",
            "on tips for leadership and management",
            "discussing why leadership is important",
            "discussing why managers are so important",
            "about what good management looks like",
            "discussing what bad leadership looks like",
            "on why it's important for managers to be hands-on",
            "discussing why it's important for managers to give their employees space",
        ],
        [
            "about career advancement",
            "on tips for career advancement",
            "discussing the downsides of career advancement",
            "discussing the upsides of career advancement",
            "on career transitions",
            "on how to make the most of a promotion",
            "on how to make the most getting promoted",
            "on dealing with having to demote an employee",
            "on being demoted",
            "on education or learning new skills",
        ],
        [
            "about work/life balance",
            "discussing tips for keeping work-life balance",
            "on a work/life balance success story",
            "about a work-life balance horror story",
            "arguing against work-life balance",
            "arguing for work-life balance",
        ],
        [
            "about personal branding",
            "about improving your personal branding",
            "on a personal branding success story",
            "on how to know whether your personal branding is lacking",
            "about strategies for networking",
            "about why networking is important",
        ],
        [
            "about how to be a good mentor",
            "on how to be a good coach",
            "on finding a mentor",
            "about finding a coach",
            "discussing what it was like to have a mentor",
            "discussing what it was like to have a good mentor",
            "discussing what it was like to have a bad mentor",
        ],
    ],
    "Business strategy and operations": [
        [
            "on maximizing sales and revenue growth",
            "on how to make sales",
            "on how to increase sales",
            "on how to make your first sale",
            "on how to maximize revenue",
            "on how to grow your revenue",
            "on how to grow your revenue",
            "on the importance of sales and revenue growth",
            "on how to deal with poor sales and revenue growth",
            "on what to do if your sales and revenue growth are worse than you expected",
        ],
        [
            "on marketing",
            "on guerrilla marketing",
            "on viral marketing",
            "on affiliate marketing",
            "on tips for marketing a new product",
            "on tips for marketing an old product in a new way",
            "on tips for marketing niche products",
            "on what good marketing looks like",
            "on what bad marketing looks like",
            "on how to measure a marketing campaign's success",
            "on strategies for marketing",
            "on conducting marketing research",
            "on tips for conducting marketing research",
            "discussing the cost of marketing",
            "discussing a case study of successful marketing",
            "discussing a case study of failed marketing",
        ],
        [
            "on building your company's brand",
            "about brand image",
            "about brand loyalty",
            "about brand awareness",
            "about brand recognition",
            "on what good branding looks like",
            "on what bad branding looks like",
            "about how a brand is recieved by the public",
            "discussing strategies for branding",
            "discussing a case study of successful branding",
            "discussing a case study of a successful re-brand",
            "discussing a case study of a failed re-brand",
        ],
        [
            "about customer success",
            "about customer retention",
            "on customer churn",
            "discussing why customer retention is important",
            "discussing why customer success is important",
            "discussing why customer churn is important",
            "how to retain customers",
            "discussing tips for retaining customers",
            "on a customer success case study",
            "on a customer churn horror story",
            "on a customer retention success story",
        ],
        [
            "on product management",
            "on how to manage a product",
            "on why product management is important",
            "on what good product management looks like",
            "on what bad product management looks like",
            "discussing a product management case study",
            "discussing a product management success story",
            "discussing a product management horror story",
        ],
        [
            "on business development",
            "on how to approach business development strategically",
            "discussing why business development is crucial for growth",
            "discussing what good business development looks like",
            "discussing what bad business development looks like",
            "a business development case study",
            "a business development success story",
            "a business development horror story",
            "on identifying the right partnership opportunities",
            "on building a BD pipeline",
            "on negotiating win-win partnerships",
            "about what founders get wrong about business development",
            "on the difference between sales and business development",
        ],
        [
            "on entrepreneurship",
            "on starting a company from scratch",
            "discussing why now is the time to build",
            "on what good entrepreneurship looks like",
            "on what bad entrepreneurship looks like",
            "about an entrepreneurship case study",
            "discussing an entrepreneurship success story",
            "on an entrepreneurship horror story",
            "on finding product-market fit",
            "on the hardest parts of being a founder",
            "discussing what I wish I knew before starting my company",
            "about the myths vs reality of startup life",
            "on knowing when to pivot vs persevere",
            "on finding your first customers",
            "discussing the unsexy truth about building a startup",
        ],
        [
            "on scaling a business",
            "on how to scale without breaking things",
            "discussing why scaling too fast can kill your company",
            "on what good scaling looks like",
            "on what bad scaling looks like",
            "discussing a business scaling case study",
            "discussing a business scaling success story",
            "discussing a business scaling horror story",
            "on when to scale vs when to optimize",
            "on building systems that scale",
            "the biggest bottlenecks when scaling",
            "what changes when you go from 10 to 100 employees",
            "on maintaining culture while scaling rapidly",
            "the operational debt that comes with hypergrowth",
        ],
        [
            "on negotiation",
            "on how to negotiate effectively",
            "discussing why negotiation is a skill everyone needs",
            "on what good negotiation looks like",
            "on what bad negotiation looks like",
            "on a negotiation case study",
            "on a negotiation success story",
            "on a negotiation horror story",
            "on preparing for high-stakes negotiations",
            "on the power of silence in negotiation",
            "on how to know what your counterpart really wants in a negotiation",
            "on walking away from bad deals",
            "the negotiation mistake that cost me",
            "on the win-win vs win-lose mindsets in negotiation",
        ],
        [
            "on data and analytics",
            "on how to use data to make better decisions",
            "about why data without context is dangerous",
            "on what good data analysis looks like",
            "on what bad data analysis looks like",
            "on a data analytics case study",
            "on a data analytics success story",
            "on a data analytics horror story",
            "on the metrics that actually matter",
            "on vanity metrics vs actionable metrics",
            "about what most people get wrong about data",
            "on building a data-driven culture",
            "on the data insight that changed our strategy",
            "on when to trust your gut vs the data",
        ],
    ],
    "Workplace culture/human resources": [
        [
            "on company culture",
            "on how to build a strong company culture",
            "discussing why company culture matters more than perks",
            "discussing what good company culture looks like",
            "discussing what bad company culture looks like",
            "on a company culture case study",
            "on a company culture success story",
            "on a company culture horror story",
            "on defining your company values",
            "on culture fit vs culture add",
            "discussing what kills company culture",
            "on maintaining culture during rapid growth",
            "on the difference between culture and vibes",
        ],
        [
            "on employee engagement",
            "on how to increase employee engagement",
            "about why employee engagement drives results",
            "discussing what good employee engagement looks like",
            "discussing what bad employee engagement looks like",
            "discussing an employee engagement case study",
            "discussing an employee engagement success story",
            "discussing an employee engagement horror story",
            "on measuring what actually matters",
            "on the disconnect between surveys and reality",
            "on what disengaged employees are really telling you",
            "on creating psychological safety at work",
            "discussing the employee engagement strategies that backfire",
        ],
        [
            "on diversity, equity, and inclusion",
            "on how to build truly inclusive teams",
            "on why DEI is a business imperative",
            "discussing what good DEI work looks like",
            "discussing what performative DEI looks like",
            "on a DEI case study",
            "on a DEI success story",
            "on a DEI failure story",
            "on moving beyond diversity theater",
            "on inclusive hiring practices",
            "discussing what companies get wrong about DEI",
            "on the difference between diversity and inclusion",
            "on building belonging, not just representation",
            "about the uncomfortable conversations about equity",
        ],
        [
            "on remote work",
            "on how to make hybrid work actually work",
            "discussing why remote work is here to stay",
            "discussing why remote work is overrated",
            "discussing what good remote work looks like",
            "discussing what bad remote work looks like",
            "discussing a remote work case study",
            "on a remote work success story",
            "on a remote work horror story",
            "on the return-to-office debate",
            "on async communication done right (in the context of remote work)",
            "on what remote-first really means",
            "on combating remote work isolation",
            "discussing the hidden costs of hybrid work",
            "on trust and autonomy in distributed teams",
        ],
        [
            "on hiring",
            "on how to hire the right people",
            "why hiring is the most important thing you do",
            "what good hiring looks like",
            "what bad hiring looks like",
            "a hiring case study",
            "a hiring success story",
            "a hiring horror story",
            "on red flags in the interview process",
            "on writing job descriptions that attract talent",
            "what candidates really want to know",
            "on the broken interview process",
            "on hiring for potential vs experience",
            "the true cost of a bad hire",
        ],
        [
            "on talent retention",
            "on how to keep your best people",
            "why retention matters more than recruitment",
            "what good retention looks like",
            "what bad retention looks like",
            "a talent retention case study",
            "a talent retention success story",
            "a talent retention horror story",
            "on why people really leave",
            "on the exit interview insights you're ignoring",
            "what retention bonuses won't fix",
            "on career pathing that actually works",
            "the early warning signs of attrition",
            "on making people want to stay",
        ],
        [
            "on team building",
            "on how to build high-performing teams",
            "why team dynamics matter more than individual talent",
            "what good team building looks like",
            "what bad team building looks like",
            "a team building case study",
            "a team building success story",
            "a team building horror story",
            "on trust exercises that aren't cringe",
            "on building teams, not groups of individuals",
            "what destroys team cohesion",
            "on psychological safety in teams",
            "the team building activities that actually work",
            "on conflict as a feature, not a bug",
        ],
    ],
    "Industry-specific": [
        [
            "on tech and software development",
            "on how to build great software",
            "why technical debt matters",
            "what good software development looks like",
            "what bad software development looks like",
            "a software development case study",
            "a software development success story",
            "a software development horror story",
            "on the engineering culture wars",
            "on shipping fast vs shipping right",
            "what non-technical founders get wrong about engineering",
            "on the state of tech hiring",
            "on open source contributions",
            "the tools and frameworks everyone's talking about",
            "on technical architecture decisions",
        ],
        [
            "on finance and investing",
            "on how to think about investments",
            "why financial literacy is crucial",
            "what good investing looks like",
            "what bad investing looks like",
            "a finance case study",
            "an investing success story",
            "an investing horror story",
            "on the current market conditions",
            "on portfolio diversification strategies",
            "what retail investors get wrong",
            "on the venture capital landscape",
            "on economic indicators worth watching",
            "the investment thesis behind [sector/company]",
            "on risk management in uncertain times",
        ],
        [
            "on healthcare and pharma",
            "on how to improve healthcare delivery",
            "why healthcare innovation matters",
            "what good healthcare looks like",
            "what broken healthcare looks like",
            "a healthcare case study",
            "a healthcare success story",
            "a healthcare horror story",
            "on patient outcomes vs patient experience",
            "on the future of digital health",
            "what's broken in the healthcare system",
            "on regulatory challenges in pharma",
            "on health equity and access",
            "the innovation happening in biotech",
            "on clinical trials and drug development",
        ],
        [
            "on manufacturing and supply chain",
            "on how to optimize supply chain operations",
            "why supply chain resilience matters",
            "what good supply chain management looks like",
            "what bad supply chain management looks like",
            "a supply chain case study",
            "a supply chain success story",
            "a supply chain horror story",
            "on the lessons from recent disruptions",
            "on nearshoring vs offshoring",
            "what just-in-time taught us",
            "on inventory management strategies",
            "on sustainability in manufacturing",
            "the technology transforming supply chains",
            "on vendor relationships and partnerships",
        ],
        [
            "on real estate",
            "on how to succeed in real estate",
            "why real estate remains a solid investment",
            "what good real estate investing looks like",
            "what bad real estate investing looks like",
            "a real estate case study",
            "a real estate success story",
            "a real estate horror story",
            "on the current housing market",
            "on commercial vs residential strategies",
            "what first-time investors get wrong",
            "on property management best practices",
            "on real estate technology and proptech",
            "the impact of interest rates on real estate",
            "on finding undervalued markets",
        ],
        [
            "on consulting",
            "on how to be a great consultant",
            "why consulting skills translate everywhere",
            "what good consulting looks like",
            "what bad consulting looks like",
            "a consulting case study",
            "a consulting success story",
            "a consulting horror story",
            "on managing difficult clients",
            "on the consulting to industry transition",
            "what clients really want from consultants",
            "on scoping and pricing consulting projects",
            "on building a consulting practice",
            "the frameworks that actually matter",
            "on delivering recommendations that get implemented",
        ],
        [
            "on legal and compliance",
            "on how to navigate legal complexity",
            "why compliance matters more than you think",
            "what good compliance looks like",
            "what bad compliance looks like",
            "a legal case study",
            "a compliance success story",
            "a compliance horror story",
            "on regulatory changes affecting businesses",
            "on contract negotiation strategies",
            "what companies miss about legal risk",
            "on building a compliance culture",
            "on data privacy and GDPR",
            "the legal implications of some new technology",
            "on when to bring in legal counsel",
        ],
        [
            "on academia",
            "on how to navigate academic careers",
            "why academic research matters beyond the ivory tower",
            "what good academia looks like",
            "what broken academia looks like",
            "an academic case study",
            "an academic success story",
            "an academic horror story",
            "on the publish-or-perish culture",
            "on transitioning from academia to industry",
            "what academia gets wrong about preparing students",
            "on securing research funding",
            "on teaching and mentorship in universities",
            "the future of higher education",
            "on academic politics and tenure",
        ],
    ],
    "Thought leadership": [
        [
            "on industry trends",
            "on how to spot trends before they peak",
            "why understanding trends matters",
            "what good trend analysis looks like",
            "what bad trend prediction looks like",
            "an industry trend case study",
            "a trend prediction success story",
            "a trend prediction failure story",
            "on the trends shaping some industry (pick one) in 2025",
            "on separating signal from noise",
            "what everyone's getting wrong about some trend (pick one)",
            "on trends that are overhyped (pick one)",
            "the undercovered trends worth watching",
            "on why some trend (pick one) is here to stay",
        ],
        [
            "on innovation and disruption",
            "on how to innovate in established markets",
            "why disruption is misunderstood",
            "what good innovation looks like",
            "what innovation theater looks like",
            "an innovation case study",
            "a disruption success story",
            "a disruption failure story",
            "on the innovator's dilemma",
            "on incumbent advantages vs startup speed",
            "what kills innovation in large companies",
            "on disruptive vs sustaining innovation",
            "on the industries ripe for disruption",
            "the innovation playbook of any company",
            "on building cultures of innovation",
        ],
        [
            "on digital transformation",
            "on how to lead digital transformation",
            "why digital transformation fails",
            "what good digital transformation looks like",
            "what digital transformation theater looks like",
            "a digital transformation case study",
            "a digital transformation success story",
            "a digital transformation horror story",
            "on change management in digital initiatives",
            "on legacy systems and technical debt",
            "what digital transformation really means",
            "on the human side of digital change",
            "on measuring digital transformation success",
            "the technologies enabling transformation",
            "on digital transformation in any industry (pick one)",
        ],
        [
            "on sustainability and ESG",
            "on how to build sustainable businesses",
            "why ESG (environmental, social, and governance) is a competitive advantage",
            "what good ESG (environmental, social, and governance) practice looks like",
            "what greenwashing looks like",
            "a sustainability case study",
            "a sustainability success story",
            "an ESG failure story",
            "on measuring real impact vs reporting metrics",
            "on the business case for sustainability",
            "what companies get wrong about ESG (environmental, social, and governance)",
            "on stakeholder capitalism",
            "on climate risk and resilience",
            "the ESG frameworks that matter",
            "on balancing profit and purpose",
        ],
        [
            "on economic analysis",
            "on how to interpret economic signals",
            "why economic literacy matters for leaders",
            "what good economic analysis looks like",
            "what bad economic analysis looks like",
            "an economic analysis case study",
            "an economic prediction success story",
            "an economic prediction failure story",
            "on the current macroeconomic environment",
            "on recession indicators and what they mean",
            "what the data is really telling us",
            "on inflation, interest rates, and business strategy",
            "on global economic shifts",
            "the economic implications of [policy/event]",
            "on reading between the lines of economic reports",
        ],
        [
            "on market insights",
            "on how to read market dynamics",
            "why market timing matters less than you think",
            "what good market analysis looks like",
            "what bad market analysis looks like",
            "a market insight case study",
            "a market call success story",
            "a market call horror story",
            "on the current state of [market/sector]",
            "on market opportunities everyone's missing",
            "what the market is pricing in",
            "on sector rotation and what it means",
            "on consumer behavior shifts",
            "the market implications of [trend/technology]",
            "on understanding market sentiment vs fundamentals",
        ],
    ],
    "Productivity": [
        [
            "on productivity hacks",
            "on how to get more done in less time",
            "why most productivity advice is wrong",
            "what good productivity looks like",
            "what productivity theater looks like",
            "a productivity case study",
            "a productivity success story",
            "a productivity horror story",
            "on the productivity systems that actually work",
            "on deep work vs busy work",
            "the productivity hack that changed everything for me (feel free to make up details, this is just for ideas!)",
            "on when productivity culture becomes toxic",
            "on doing less but better",
            "the tools I use to stay productive (feel free to make up any details, this is just for ideas!)",
        ],
        [
            "on time management",
            "on how to manage your time effectively",
            "why time management is really priority management",
            "what good time management looks like",
            "what bad time management looks like",
            "a time management case study",
            "a time management success story",
            "a time management horror story",
            "on protecting your calendar",
            "on the myth of work-life balance",
            "what time blocking gets wrong",
            "on saying no to protect your time",
            "the time management mistakes people make",
            "on timeboxing vs task lists",
        ],
        [
            "on email communication",
            "on how to write emails people actually read",
            "why most emails are too long",
            "what good email communication looks like",
            "what bad email communication looks like",
            "an email communication case study",
            "an email communication success story",
            "an email communication horror story",
            "on inbox zero and why it matters",
            "on inbox zero and why it doesn't matter",
            "on the art of the cold email",
            "what your email response time says about you",
            "on async communication etiquette",
            "the email templates that get responses",
            "on when to pick up the phone instead",
        ],
        [
            "on meetings",
            "on how to run meetings that don't waste time",
            "why most meetings should be emails",
            "what good meetings look like",
            "what bad meetings look like",
            "a meeting optimization case study",
            "a meeting optimization success story",
            "a meeting optimization horror story",
            "on the meetings you should cancel today",
            "on meeting hygiene and etiquette",
            "what effective meeting agendas look like",
            "on the cost of unnecessary meetings",
            "the meeting format that changed our team (feel free to make up any details, this is just for ideas!)",
            "on decision meetings vs discussion meetings",
        ],
        [
            "on project management",
            "on how to manage projects that ship on time",
            "why project management is about people, not tools",
            "what good project management looks like",
            "what bad project management looks like",
            "a project management case study",
            "a project management success story",
            "a project management horror story",
            "on scope creep and how to prevent it",
            "on the project management frameworks that work",
            "what project managers get wrong",
            "on managing stakeholder expectations",
            "the project management skill no one talks about",
            "on agile vs waterfall (and when to use each)",
        ],
    ],
    "Soft skills/mindset": [
        [
            "on communication skills",
            "on how to communicate more effectively",
            "why communication is the most underrated skill",
            "what good communication looks like",
            "what bad communication looks like",
            "a communication case study",
            "a communication success story",
            "a communication horror story",
            "on the art of clear writing",
            "on difficult conversations",
            "what poor communicators don't realize",
            "on listening as a superpower",
            "the communication habits that hold you back",
            "on saying no with grace",
        ],
        [
            "on emotional intelligence",
            "on how to develop emotional intelligence",
            "why EQ matters more than IQ",
            "what good emotional intelligence looks like",
            "what bad emotional intelligence looks like",
            "an emotional intelligence case study",
            "an emotional intelligence success story",
            "an emotional intelligence horror story",
            "on self-awareness in leadership",
            "on reading the room",
            "what emotionally intelligent leaders do differently",
            "on managing your reactions",
            "the subtle signs of low emotional intelligence",
            "on empathy vs sympathy",
        ],
        [
            "on resilience",
            "on how to bounce back from failure",
            "why failure is the best teacher",
            "what good resilience looks like",
            "what toxic resilience looks like",
            "a resilience case study",
            "a resilience success story",
            "a failure story that changed everything",
            "on the lessons from my biggest failure",
            "on embracing setbacks",
            "what failure taught me about success",
            "on the difference between resilience and stubbornness",
            "the hidden gift in rejection",
            "on when to quit vs when to persist",
        ],
        [
            "on authenticity",
            "on how to be more authentic at work",
            "why vulnerability is strength",
            "what good authenticity looks like",
            "what performative vulnerability looks like",
            "an authenticity case study",
            "an authenticity success story",
            "a vulnerability horror story",
            "on showing up as your whole self",
            "on the masks we wear at work",
            "what authentic leadership really means",
            "on oversharing vs being real",
            "the power of admitting you don't know",
            "on vulnerability without the trauma dumping",
        ],
        [
            "on decision-making",
            "on how to make better decisions",
            "why decision-making is a learnable skill",
            "what good decision-making looks like",
            "what bad decision-making looks like",
            "a decision-making case study",
            "a decision-making success story",
            "a decision-making horror story",
            "on trusting your gut vs data",
            "on making decisions with incomplete information",
            "what separates good from great decision-makers",
            "on the decisions you're avoiding",
            "the framework I use for tough calls",
            "on reversible vs irreversible decisions",
        ],
        [
            "on critical thinking",
            "on how to think more critically",
            "why critical thinking matters in the age of AI",
            "what good critical thinking looks like",
            "what bad critical thinking looks like",
            "a critical thinking case study",
            "a critical thinking success story",
            "a critical thinking horror story",
            "on questioning assumptions",
            "on spotting logical fallacies",
            "what critical thinkers do differently",
            "on first principles thinking",
            "the questions you should be asking",
            "on avoiding groupthink",
        ],
        [
            "on collaboration",
            "on how to collaborate effectively",
            "why collaboration beats individual genius",
            "what good collaboration looks like",
            "what bad collaboration looks like",
            "a collaboration case study",
            "a collaboration success story",
            "a collaboration horror story",
            "on cross-functional teamwork",
            "on collaboration vs consensus",
            "what kills collaborative culture",
            "on working with difficult people",
            "the collaboration traps to avoid",
            "on knowing when to collaborate vs go solo",
        ],
    ],
    "Self-promotion": [
        [
            "on the journey from broke to successful",
            "about the journey from employee to entrepreneur",
            "on the journey from rejection to acceptance",
            "about the journey from burnout to balance",
            "on the journey from corporate to startup",
            "on the journey from failure to comeback",
            "about the journey from self-doubt to confidence",
            "about how I went from sleeping on couches to running a company",
            "on how I went from 100 rejections to landing my dream role",
            "about a 5-year overnight success story",
            "about a 10-year overnight success story",
            "about going from laid off to thriving",
            "on going from side hustle to full-time founder",
            "on my non-linear career path",
            "on the pivot that changed everything",
        ],
        [
            "about how grateful I am for the incredible team that I built",
            "about how I didn't expect this award but it means everything",
            "about how I'm spending another late night at the office",
            "about being a kid from a small town who dreamed big",
            "about how I never thought I'd be speaking at this prestigious event",
            "about how 5 years ago I had nothing, today I have everything",
            "about blessed to work with these amazing clients",
            "about how I'm honestly overwhelmed by all the opportunities coming my way",
            "about how my inbox is flooded but I love what I do",
            "about how turning down opportunities is the hardest part of success",
            "about imposter syndrome hitting different when I reached a recent impressive milestone",
            "with a reminder that hard work pays off",
        ],
        [
            "about how we're hiring and here's what that taught me about growth",
            "about how we just raised our Series A and here's what I learned",
            "about how we hit our ARR target",
            "about how we're launching our new product and why timing is everything",
            "about how we just signed our biggest client and here's what it took",
            "about how we're opening a new office and here's why location matters",
            "about how we made the Inc 5000 list and here's what nobody tells you",
            "about how we're acquiring another company and here's what I learned about M&A",
            "about how we just won an industry award and here's what it means",
            "about how we're rebranding and here's why authenticity matters",
            "about how our team just hit 100 people and here's what changed",
            "about how we're going remote-first and here's the lesson",
        ],
        [
            "about how I'm honored to be named on a prestigious list",
            "about how I was humbled to receive an industry award",
            "about how grateful to be recognized with a new title",
            "about how I'm excited to share we won an award",
            "about how thrilled I am to be featured in a major publication",
            "about how I just made the 30 under 30 list",
            "about how I just made the 40 under 40 list",
            "about how I was selected to speak at a prestigious conference",
        ],
        [
            "on what I learned from getting fired",
            "on what I learned from my startup failing",
            "on what I learned from hitting rock bottom",
            "on what I learned from my first $1M year",
            "on what I learned from scaling to 100 employees",
            "on what I learned from pivoting our entire business model",
            "on what I learned from almost running out of cash",
            "on what I learned from losing our biggest client",
            "on what I learned from being rejected 50 times",
            "on what I learned from my TED talk",
            "on what I learned from our acquisition",
            "on what I learned from going viral",
            "on what I learned from taking a sabbatical",
            "on what I learned from hiring my first executive",
            "on what I learned from missing payroll",
            "on what I learned from my mentor",
            "on what I learned from being underestimated",
            "on what I learned from my first million-dollar mistake",
        ],
    ],
    "Meta-LinkedIn Content": [
        [
            "on how to post on LinkedIn",
            "on how to write posts that actually get engagement",
            "about why most LinkedIn posts fail",
            "about what good LinkedIn posts look like",
            "about what bad LinkedIn posts look like",
            "on a LinkedIn posting case study",
            "on a LinkedIn posting success story",
            "on a LinkedIn posting horror story",
            "on the anatomy of a viral LinkedIn post",
            "on posting frequency and timing",
            "on what hooks actually work on LinkedIn",
            "on the formats that perform best",
            "on the LinkedIn posting mistakes everyone makes",
            "on writing for the LinkedIn feed",
        ],
        [
            "on the LinkedIn algorithm",
            "on how to beat the LinkedIn algorithm",
            "about why understanding the algorithm matters",
            "about what good algorithm strategy looks like",
            "about what algorithm gaming looks like",
            "on a LinkedIn algorithm case study",
            "on a LinkedIn algorithm success story",
            "on a LinkedIn algorithm horror story",
            "on what the algorithm actually rewards on LinkedIn",
            "on engagement bait vs genuine engagement on LinkedIn",
            "on what kills your LinkedIn reach",
            "on the algorithm changes you need to know for LinkedIn",
            "on the algorithm hacks that actually work on LinkedIn",
            "on impressions vs meaningful connections",
        ],
        [
            "on personal branding on LinkedIn",
            "on how to build your personal brand",
            "why your personal brand matters more than ever",
            "what good personal branding looks like",
            "what cringe personal branding looks like",
            "a personal branding case study",
            "a personal branding success story",
            "a personal branding horror story",
            "on finding your unique voice",
            "on consistency vs authenticity in branding",
            "what your LinkedIn presence says about you",
            "on building authority in your niche",
            "the personal branding mistakes that hurt you",
            "on standing out without selling out",
        ],
        [
            "on authenticity on social media",
            "on how to be authentic online",
            "about why authenticity wins on LinkedIn",
            "about what genuine authenticity looks like",
            "about what performative authenticity looks like",
            "an authenticity case study",
            "an authenticity success story",
            "an authenticity horror story",
            "on the line between authentic and oversharing",
            "on vulnerability as a strategy vs vulnerability as truth",
            "about what authenticity theater looks like",
            "on being real in a curated world",
            "about the authenticity paradox on LinkedIn",
            "on when 'being yourself' isn't enough",
        ],
    ],
}
